components:
  schemas:
    github.com.arravoco.hackathon_backend.data.CreateParticipantAccountData:
      properties:
        Email:
          type: string
        FirstName:
          type: string
        Gender:
          type: string
        GithubAddress:
          type: string
        LastName:
          type: string
        LinkedInAddress:
          type: string
        PasswordHash:
          type: string
        Role:
          type: string
        State:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.data.CreateUserAccountData:
      properties:
        Email:
          type: string
        FirstName:
          type: string
        Gender:
          type: string
        LastName:
          type: string
        PasswordHash:
          type: string
        Role:
          type: string
        State:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.dtos.AuthParticipantInfoUpdateDTO:
      properties:
        email:
          type: string
        first_name:
          type: string
        gender:
          type: string
        github_address:
          type: string
        last_name:
          type: string
        linkedIn_address:
          type: string
        state:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.dtos.AuthUserInfoUpdateDTO:
      properties:
        email:
          type: string
        first_name:
          type: string
        gender:
          type: string
        last_name:
          type: string
        state:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.dtos.ChangePasswordDTO:
      properties:
        new_password:
          type: string
        old_password:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.dtos.CompleteEmailVerificationDTO:
      properties:
        email:
          type: string
        token:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.dtos.CompletePasswordRecoveryDTO:
      properties:
        email:
          type: string
        new_password:
          type: string
        token:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.entity.Judge:
      properties:
        email:
          type: string
        first_name:
          type: string
        gender:
          type: string
        last_name:
          type: string
        passwordHash:
          type: string
        role:
          type: string
        state:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.entity.Participant:
      properties:
        email:
          type: string
        first_name:
          type: string
        gender:
          type: string
        github_address:
          type: string
        last_name:
          type: string
        linkedIn_address:
          type: string
        passwordHash:
          type: string
        role:
          type: string
        state:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchFailureResponse:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchSuccessResponse:
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchSuccessResponseData'
          type: object
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchSuccessResponseData:
      properties:
        email:
          type: string
        first_name:
          type: string
        gender:
          type: string
        github_address:
          type: string
        last_name:
          type: string
        linkedIn_address:
          type: string
        passwordHash:
          type: string
        role:
          type: string
        state:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.BasicLoginDTO:
      properties:
        identifier:
          type: string
        password:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.BasicLoginFailureResponse:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.BasicLoginSuccessResponse:
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.BasicLoginSuccessResponseData'
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.BasicLoginSuccessResponseData:
      properties:
        access_token:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationFailureResponse:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationSuccessResponse:
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationSuccessResponseData'
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationSuccessResponseData:
      properties:
        email:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.CompletePasswordRecoveryFailureResponse:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.CompletePasswordRecoverySuccessResponse:
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationSuccessResponseData'
          type: object
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationFailureResponse:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationSuccessResponse:
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationSuccessResponseData'
          type: object
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationSuccessResponseData:
      properties:
        email:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.PasswordChangeFailureResponse:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.PasswordChangeSuccessResponse:
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.PasswordChangeSuccessResponseData'
          type: object
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.PasswordChangeSuccessResponseData:
      type: object
    github.com.arravoco.hackathon_backend.routes.RegisterParticipantFailResponse:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.RegisterParticipantSuccessResponse:
      properties:
        Data:
          $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.data.CreateParticipantAccountData'
          type: object
        code:
          type: integer
        message:
          type: string
      type: object
    github.com.arravoco.hackathon_backend.routes.ResponseData:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
info:
  contact:
    email: appdev@arravo.co
    name: David Alabi
  description: API usually works as expected. But sometimes its not true.
  license:
    name: MIT
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: http://arravo.co/contact
  title: Hackathon Backend API
  version: 1.0.0
openapi: 3.0.0
paths:
  /api/auth/login:
    post:
      description: ' Log a user in'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.BasicLoginDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.BasicLoginSuccessResponse'
          description: Users Responses JSON
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.BasicLoginFailureResponse'
          description: hhhh
      tags:
      - users
  /api/auth/me:
    get:
      description: ' Get auth user information "Type ''Bearer TOKEN'' to correctly
        set the Bearer token"'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchSuccessResponse'
          description: UserInfo fetched successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchFailureResponse'
          description: UserInfo fetch failed
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchFailureResponse'
          description: UserInfo fetch failed
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchFailureResponse'
          description: UserInfo fetch failed
    put:
      description: ' Get auth user information'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.dtos.AuthParticipantInfoUpdateDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchSuccessResponse'
          description: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchFailureResponse'
          description: ""
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchFailureResponse'
          description: ""
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.AuthUserInfoFetchFailureResponse'
          description: ""
  /api/auth/password/change:
    post:
      description: ' Verify user email address'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.dtos.ChangePasswordDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.PasswordChangeSuccessResponse'
          description: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.PasswordChangeFailureResponse'
          description: ""
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.PasswordChangeFailureResponse'
          description: ""
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.PasswordChangeFailureResponse'
          description: ""
  /api/auth/password/recovery/completion:
    post:
      description: ' Verify user email address'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.dtos.CompletePasswordRecoveryDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompletePasswordRecoverySuccessResponse'
          description: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompletePasswordRecoveryFailureResponse'
          description: ""
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompletePasswordRecoveryFailureResponse'
          description: ""
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompletePasswordRecoveryFailureResponse'
          description: ""
  /api/auth/password/recovery/initiation:
    get:
      description: ' recover password'
      parameters:
      - description: Email to verify
        in: query
        name: email
        schema:
          description: Email to verify
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationSuccessResponse'
          description: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationFailureResponse'
          description: ""
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationFailureResponse'
          description: ""
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationFailureResponse'
          description: ""
  /api/auth/verification/email/completion:
    post:
      description: ' Verify user email address'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.dtos.CompleteEmailVerificationDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationSuccessResponse'
          description: Email verification successful
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationFailureResponse'
          description: Email verification failed
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationFailureResponse'
          description: Email verification failed
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.CompleteEmailVerificationFailureResponse'
          description: Email verification failed
  /api/auth/verification/email/initiation:
    get:
      description: ' Verify user email address'
      parameters:
      - description: Email to verify
        in: query
        name: email
        schema:
          description: Email to verify
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationSuccessResponse'
          description: Verification succeeded
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationFailureResponse'
          description: Verification failed
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationFailureResponse'
          description: Verification failed
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.InitiateEmailVerificationFailureResponse'
          description: Verification failed
  /api/judges:
    post:
      description: ' Register new participant'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.RegisterParticipantSuccessResponse'
          description: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.RegisterParticipantFailResponse'
          description: ""
  /api/participants:
    post:
      description: ' Register new participant'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.RegisterParticipantSuccessResponse'
          description: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github.com.arravoco.hackathon_backend.routes.RegisterParticipantFailResponse'
          description: ""
servers:
- description: ' Localhost'
  url: localhost:5000
- description: ' Main'
  url: http://www.fake2.com
