definitions:
  data.CreateParticipantAccountData:
    properties:
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      githubAddress:
        type: string
      lastName:
        type: string
      linkedInAddress:
        type: string
      passwordHash:
        type: string
      state:
        type: string
    type: object
  routes.BasicLoginFailureResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  routes.BasicLoginSuccessResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/routes.BasicLoginSuccessResponseData'
      message:
        type: string
    type: object
  routes.BasicLoginSuccessResponseData:
    properties:
      access_token:
        type: string
    type: object
  routes.RegisterParticipantFailResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  routes.RegisterParticipantSuccessResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/data.CreateParticipantAccountData'
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/login:
    post:
      description: Log a user in
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.BasicLoginSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/routes.BasicLoginFailureResponse'
      summary: Log a user in
      tags:
      - Auth
  /api/participants:
    post:
      description: Register new participant
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.RegisterParticipantSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/routes.RegisterParticipantFailResponse'
      summary: Register new participant
      tags:
      - Participants
  /participants:
    put:
      description: Update participant's information
      produces:
      - application/json
      responses: {}
      summary: Update participant's information
      tags:
      - Participants
swagger: "2.0"
